import tempfile
import threading
import unittest
from pathlib import Path

import numpy as np

from csv_analyzer.data import CancelledError, DataError, ImportOptions, load_dataset
from csv_analyzer.state import AppState, FilterRule


class ImportTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)

    def write(self, text, name="data.csv", encoding="utf-8"):
        path = Path(self.temp.name) / name
        path.write_text(text, encoding=encoding)
        return path

    def test_dat_commented_header_preserves_first_row(self):
        ds = load_dataset(self.write("# x y\n1 2\n3 4\n", "scan.dat"))
        self.assertEqual(ds.frame.values.tolist(), [[1, 2], [3, 4]])
        self.assertEqual(list(ds.frame), ["x", "y"])

    def test_headerless_dat_and_ordinary_header(self):
        ds = load_dataset(self.write("1 2\n3 4\n", "scan.dat"))
        self.assertEqual(len(ds.frame), 2)
        ds = load_dataset(self.write("x y\n1 2\n", "scan.dat"), ImportOptions(header="yes"))
        self.assertEqual(ds.frame.values.tolist(), [[1, 2]])

    def test_explicit_dat_header_skips_leading_metadata_comments(self):
        path = self.write("# generated by instrument\n# run 42\nx y\n1 2\n", "scan.dat")
        ds = load_dataset(path, ImportOptions(header="yes"))
        self.assertEqual(ds.frame.columns.tolist(), ["x", "y"])
        self.assertEqual(ds.frame.values.tolist(), [[1, 2]])

    def test_csv_delimiters_decimal_and_encoding(self):
        path = self.write("café;value\na;1,5\n", encoding="cp1252")
        ds = load_dataset(path, ImportOptions(encoding="cp1252", decimal=","))
        self.assertEqual(ds.frame["value"].iloc[0], 1.5)
        self.assertEqual(ds.delimiter, ";")
        with self.assertRaises(DataError):
            load_dataset(path)

    def test_quoted_newlines_and_delimiters(self):
        ds = load_dataset(self.write('label,x\n"a,b",1\n"two\nlines",2\n'))
        self.assertEqual(ds.frame["label"].tolist(), ["a,b", "two\nlines"])

    def test_blank_lines_and_quoted_empty_records_are_distinct(self):
        ds = load_dataset(self.write(' \t \nvalue\n   \n""\n"   "\n5\n\t\n'))
        self.assertEqual(len(ds.frame), 3)
        self.assertTrue(ds.frame.iloc[0].isna().all())
        self.assertEqual(ds.frame.iloc[1, 0], "   ")
        ds = load_dataset(self.write("x,y\n  \n1,2\n\t \n3,4\n"))
        self.assertEqual(ds.frame.values.tolist(), [[1, 2], [3, 4]])

    def test_dat_literal_apostrophes_backslashes_and_quoted_comments(self):
        ds = load_dataset(
            self.write('# "a label" value\n"a # b" 1 # note\ndon\'t 2\nC:\\data 3\n', "scan.dat")
        )
        self.assertEqual(ds.frame.columns.tolist(), ["a label", "value"])
        self.assertEqual(ds.frame.iloc[:, 0].tolist(), ["a # b", "don't", "C:\\data"])
        ds = load_dataset(self.write('# "a ""quote""" y\n1 2\n', "scan.dat"))
        self.assertEqual(ds.frame.columns.tolist(), ['a "quote"', "y"])

    def test_dat_quoted_empty_field_and_malformed_quote(self):
        ds = load_dataset(self.write('# x y\n"" 2\n', "scan.dat"))
        self.assertEqual(ds.missing_count, 1)
        with self.assertRaisesRegex(DataError, "Unclosed quote"):
            load_dataset(self.write('# x y\n"unfinished 2\n', "scan.dat"))

    def test_bad_widths_never_infer_an_index(self):
        for text in ("x,y\n1,2,3\n4,5,6\n", "x,y\n1,2\n3\n"):
            with self.subTest(text=text), self.assertRaises(DataError):
                load_dataset(self.write(text))

    def test_empty_and_header_only(self):
        with self.assertRaises(DataError):
            load_dataset(self.write(""))
        ds = load_dataset(self.write("x,y\n"))
        self.assertEqual(ds.frame.shape, (0, 2))
        self.assertTrue(ds.notices)

    def test_duplicate_blank_and_colliding_headers(self):
        ds = load_dataset(self.write("x,x,x [2],,Column_4\n1,2,3,4,5\n"))
        self.assertTrue(ds.frame.columns.is_unique)
        self.assertEqual(ds.frame.iloc[0].tolist(), [1, 2, 3, 4, 5])
        self.assertGreaterEqual(len(ds.notices), 2)

    def test_missing_infinite_mixed_and_precision(self):
        ds = load_dataset(self.write("x,y,z\n1,inf,1.2345678901234567\n,2,3e-120\n3,text,4\n"))
        self.assertEqual(ds.missing_count, 1)
        self.assertEqual(ds.columns[1].kind, "text")
        self.assertEqual(ds.frame.z.iloc[0], float("1.2345678901234567"))
        ds = load_dataset(self.write("x\ninf\n-inf\n1\n"))
        self.assertEqual(ds.infinite_count, 2)

    def test_cancel_missing_file_and_iso_dates(self):
        event = threading.Event()
        event.set()
        with self.assertRaises(CancelledError):
            load_dataset(self.write("x\n1\n"), cancel=event)
        with self.assertRaises(DataError):
            load_dataset(Path(self.temp.name) / "missing.csv")
        ds = load_dataset(
            self.write("date,x\n2026-01-01,1\n"), ImportOptions(date_columns=("date",))
        )
        self.assertEqual(ds.columns[0].kind, "datetime")

    def test_state_atomic_replacement_and_stale_results(self):
        state = AppState()
        a = load_dataset(self.write("x,y\n1,2\n3,4\n"))
        b = load_dataset(self.write("a,b\n5,6\n", "b.csv"))
        notices = []
        state.subscribe(lambda reason: notices.append((reason, state.dataset.path.name)))
        ticket = state.begin_load()
        self.assertTrue(state.commit_dataset(ticket, a))
        rev = state.revision
        rules = (FilterRule("x", 2, None),)
        state.commit_filters(rev, rules, np.array([False, True]))
        self.assertEqual(state.selected_count, 1)
        self.assertFalse(state.mask.flags.writeable)
        stale = state.begin_load()
        current = state.begin_load()
        self.assertFalse(state.commit_dataset(stale, b))
        self.assertIs(state.dataset, a)
        state.cancel_load()
        self.assertFalse(state.commit_dataset(current, b))
        self.assertTrue(state.commit_dataset(state.begin_load(), b))
        self.assertEqual(state.filters, ())
        self.assertIsNone(state.mask)
        self.assertFalse(state.commit_filters(rev, rules, np.array([True])))
        self.assertEqual(notices[-1], ("dataset", "b.csv"))


if __name__ == "__main__":
    unittest.main()
